// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sut.se.enterprise.domain;

import sut.se.enterprise.domain.Enterprise;

privileged aspect Enterprise_Roo_JavaBean {
    
    public String Enterprise.getName() {
        return this.name;
    }
    
    public void Enterprise.setName(String name) {
        this.name = name;
    }
    
}
