// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sut.se.enterprise.domain;

import org.springframework.beans.factory.annotation.Configurable;
import sut.se.enterprise.domain.Enterprise;

privileged aspect Enterprise_Roo_Configurable {
    
    declare @type: Enterprise: @Configurable;
    
}
